using System.Text;

using Microsoft.CodeAnalysis;

namespace PANiXiDA.Core.Domain.Generators;

internal static class EnumerationSourceBuilder
{
    public static string Build(INamedTypeSymbol type)
    {
        var builder = new StringBuilder("// <auto-generated/>\n#nullable enable\n\n");
        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine(";");
            builder.AppendLine();
        }

        var containers = new Stack<INamedTypeSymbol>();
        for (var current = type.ContainingType; current is not null; current = current.ContainingType)
        {
            containers.Push(current);
        }

        int depth = 0;
        foreach (var container in containers)
        {
            AppendType(builder, container, depth++);
            builder.AppendLine().Append(' ', (depth - 1) * 4).AppendLine("{");
        }

        string typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string contract = "global::PANiXiDA.Core.Domain.Abstractions.IEnumerationValues<" + typeName + ">";
        AppendType(builder, type, depth);
        builder.Append(" : ").AppendLine(contract);
        builder.Append(' ', depth * 4).AppendLine("{");
        string indent = new(' ', (depth + 1) * 4);
        builder.Append(indent).Append("static global::System.Collections.Generic.IEnumerable<")
            .Append(typeName).Append("> ").Append(contract).AppendLine(".GetDeclaredValues()");
        builder.Append(indent).AppendLine("{");

        int index = 0;
        foreach (var field in type.GetMembers().OfType<IFieldSymbol>()
                     .Where(field => field.IsStatic && field.DeclaredAccessibility == Accessibility.Public
                         && !field.IsImplicitlyDeclared))
        {
            builder.Append(indent).Append("    if ((object?)").Append(typeName).Append(".@")
                .Append(field.Name).Append(" is ").Append(typeName).Append(" value").Append(index).AppendLine(")");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).Append("        yield return value").Append(index).AppendLine(";");
            builder.Append(indent).AppendLine("    }");
            index++;
        }

        builder.Append(indent).AppendLine("    yield break;");
        builder.Append(indent).AppendLine("}");
        builder.Append(' ', depth * 4).AppendLine("}");
        while (depth > 0)
        {
            builder.Append(' ', --depth * 4).AppendLine("}");
        }

        return builder.ToString().Replace("\r\n", "\n");
    }

    private static void AppendType(StringBuilder builder, INamedTypeSymbol type, int depth)
    {
        builder.Append(' ', depth * 4);
        if (type.IsReadOnly)
        {
            builder.Append("readonly ");
        }

        if (type.IsRefLikeType)
        {
            builder.Append("ref ");
        }

        builder.Append("partial ");
        if (type.IsRecord)
        {
            builder.Append("record ");
        }

        builder.Append(type.TypeKind switch
        {
            TypeKind.Struct => "struct @",
            TypeKind.Interface => "interface @",
            _ => "class @"
        }).Append(type.Name);
        if (type.TypeParameters.Length > 0)
        {
            builder.Append('<').Append(string.Join(", ", type.TypeParameters.Select(parameter => "@" + parameter.Name)))
                .Append('>');
        }
    }
}
