using System.Text;

using Microsoft.CodeAnalysis;

namespace PANiXiDA.Core.Domain.Generators;

internal static class EnumerationSourceBuilder
{
    public static string Build(INamedTypeSymbol type)
    {
        var builder = new StringBuilder("// <auto-generated/>\n#nullable enable\n\n");
        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine(";");
            builder.AppendLine();
        }

        var containers = new Stack<INamedTypeSymbol>();
        for (var current = type.ContainingType; current is not null; current = current.ContainingType)
        {
            containers.Push(current);
        }

        int depth = 0;
        foreach (var container in containers)
        {
            AppendType(builder, container, depth++);
            builder.AppendLine().Append(' ', (depth - 1) * 4).AppendLine("{");
        }

        string typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string baseTypeName = "global::PANiXiDA.Core.Domain.Enumeration<" + typeName + ">";
        string listTypeName = "global::System.Collections.Generic.IReadOnlyList<" + typeName + ">";
        string contract = "global::PANiXiDA.Core.Domain.Abstractions.IEnumerationValues<" + typeName + ">";
        var memberNames = new HashSet<string>(type.TypeParameters.Select(parameter => parameter.Name));
        for (var current = type; current is not null; current = current.BaseType)
        {
            memberNames.UnionWith(current.GetMembers().Select(member => member.Name));
        }

        string valuesFieldName = "__enumerationValues";
        while (!memberNames.Add(valuesFieldName))
        {
            valuesFieldName += "_";
        }

        AppendType(builder, type, depth);
        builder.Append(" : ").AppendLine(contract);
        builder.Append(' ', depth * 4).AppendLine("{");
        string indent = new(' ', (depth + 1) * 4);
        builder.Append(indent).Append("static ").Append(listTypeName).Append(' ').Append(contract)
            .Append(".GetDeclaredValues() => ").Append(valuesFieldName).AppendLine(".Value;");
        builder.AppendLine();
        builder.Append(indent).Append("private static readonly global::System.Lazy<").Append(listTypeName)
            .Append("> ").Append(valuesFieldName).AppendLine(" = new(static () =>");
        builder.Append(indent).AppendLine("{");
        builder.Append(indent).Append("    var items = new global::System.Collections.Generic.List<")
            .Append(typeName).AppendLine(">();");

        int index = 0;
        foreach (var field in type.GetMembers().OfType<IFieldSymbol>()
                     .Where(field => field.IsStatic && field.DeclaredAccessibility == Accessibility.Public
                         && !field.IsImplicitlyDeclared))
        {
            builder.Append(indent).Append("    if ((object?)").Append(typeName).Append(".@")
                .Append(field.Name).Append(" is ").Append(typeName).Append(" value").Append(index).AppendLine(")");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).Append("        items.Add(value").Append(index).AppendLine(");");
            builder.Append(indent).AppendLine("    }");
            index++;
        }

        builder.AppendLine();
        string initialization = $$"""
            for (int index = 0; index < items.Count; index++)
            {
                {{baseTypeName}} item = items[index];
                for (int previous = 0; previous < index; previous++)
                {
                    if ((({{baseTypeName}})items[previous]).Id == item.Id)
                    {
                        throw new global::System.InvalidOperationException(
                            $"Duplicate id '{item.Id}' in {typeof({{typeName}}).Name}");
                    }
                }

                global::System.ArgumentNullException.ThrowIfNull(item.Name, "key");
                for (int previous = 0; previous < index; previous++)
                {
                    if (global::System.String.Equals((({{baseTypeName}})items[previous]).Name,
                        item.Name, global::System.StringComparison.Ordinal))
                    {
                        throw new global::System.InvalidOperationException(
                            $"Duplicate name '{item.Name}' in {typeof({{typeName}}).Name}");
                    }
                }
            }

            items.Sort(static (left, right) =>
                (({{baseTypeName}})left).Id.CompareTo((({{baseTypeName}})right).Id));
            return items.AsReadOnly();
            """;
        foreach (string line in initialization.Replace("\r\n", "\n").Split('\n'))
        {
            builder.Append(indent).Append("    ").AppendLine(line);
        }

        builder.Append(indent).AppendLine("});");
        builder.Append(' ', depth * 4).AppendLine("}");
        while (depth > 0)
        {
            builder.Append(' ', --depth * 4).AppendLine("}");
        }

        return builder.ToString().Replace("\r\n", "\n");
    }

    private static void AppendType(StringBuilder builder, INamedTypeSymbol type, int depth)
    {
        builder.Append(' ', depth * 4);
        if (type.IsReadOnly)
        {
            builder.Append("readonly ");
        }

        if (type.IsRefLikeType)
        {
            builder.Append("ref ");
        }

        builder.Append("partial ");
        if (type.IsRecord)
        {
            builder.Append("record ");
        }

        builder.Append(type.TypeKind switch
        {
            TypeKind.Struct => "struct @",
            TypeKind.Interface => "interface @",
            _ => "class @"
        }).Append(type.Name);
        if (type.TypeParameters.Length > 0)
        {
            builder.Append('<').Append(string.Join(", ", type.TypeParameters.Select(parameter => "@" + parameter.Name)))
                .Append('>');
        }
    }
}
