using System.Text;

using Microsoft.CodeAnalysis;

namespace PANiXiDA.Core.Domain.Generators;

internal static class TypeSourceBuilder
{
    public static (StringBuilder Builder, int Depth) Begin(INamedTypeSymbol type)
    {
        var builder = new StringBuilder("// <auto-generated/>\n#nullable enable\n\n");
        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine(";");
            builder.AppendLine();
        }

        var containers = new Stack<INamedTypeSymbol>();
        for (var current = type.ContainingType; current is not null; current = current.ContainingType)
        {
            containers.Push(current);
        }

        int depth = 0;
        foreach (var container in containers)
        {
            AppendType(builder, container, depth++);
            builder.AppendLine().Append(' ', (depth - 1) * 4).AppendLine("{");
        }

        AppendType(builder, type, depth);
        builder.AppendLine().Append(' ', depth * 4).AppendLine("{");
        return (builder, depth);
    }

    public static string Complete(StringBuilder builder, int depth)
    {
        builder.Append(' ', depth * 4).AppendLine("}");
        while (depth > 0)
        {
            builder.Append(' ', --depth * 4).AppendLine("}");
        }

        return builder.ToString().Replace("\r\n", "\n");
    }

    public static string GetHintName(INamedTypeSymbol type, string suffix)
    {
        var names = new Stack<string>();
        for (var current = type; current is not null; current = current.ContainingType)
        {
            names.Push(current.MetadataName);
        }

        string prefix = type.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : type.ContainingNamespace.ToDisplayString().Replace("@", string.Empty) + ".";

        return prefix + string.Join("+", names) + "." + suffix + ".g.cs";
    }

    private static void AppendType(StringBuilder builder, INamedTypeSymbol type, int depth)
    {
        builder.Append(' ', depth * 4);
        if (type.IsReadOnly)
        {
            builder.Append("readonly ");
        }

        if (type.IsRefLikeType)
        {
            builder.Append("ref ");
        }

        builder.Append("partial ");
        if (type.IsRecord)
        {
            builder.Append("record ");
        }

        builder.Append(type.TypeKind switch
        {
            TypeKind.Struct => "struct @",
            TypeKind.Interface => "interface @",
            _ => "class @"
        }).Append(type.Name);
        if (type.TypeParameters.Length > 0)
        {
            builder.Append('<').Append(string.Join(", ", type.TypeParameters.Select(parameter => "@" + parameter.Name)))
                .Append('>');
        }
    }
}
