<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\PANiXiDA.Core.Domain\PANiXiDA.Core.Domain.csproj" />
      <ProjectReference Include="../../src/PANiXiDA.Core.Domain.Generators/PANiXiDA.Core.Domain.Generators.csproj"
                        OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
        <Using Include="FluentAssertions" />
    </ItemGroup>
</Project>
