name: CI

on:
    push:
        branches: [ main ]
    pull_request:

permissions:
    contents: read
    packages: write

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v7

          - uses: actions/setup-dotnet@v6
            with:
              dotnet-version: '10.0.x'

          - name: Create nuget.config
            if: ${{ vars.NUGET_CONFIG != '' }}
            env:
              NUGET_CONFIG: ${{ vars.NUGET_CONFIG }}
              NUGET_PROVIDER: ${{ vars.NUGET_PROVIDER }}
              REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
              REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
            run: echo "$NUGET_CONFIG" | envsubst > nuget.config

          - name: Cache NuGet packages
            uses: actions/cache@v6
            with:
              path: ~/.nuget/packages
              key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj', 'Directory.Packages.props') }}
              restore-keys: |
                nuget-${{ runner.os }}-

          - name: Restore .NET solution
            run: dotnet restore

          - name: Build source generators for formatting
            run: dotnet build src/PANiXiDA.Core.Domain.Generators/PANiXiDA.Core.Domain.Generators.csproj --no-restore

          - name: Run .NET format
            run: dotnet format --verify-no-changes --severity warn --no-restore
        
    tests:
        uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/dotnet-tests.yml@main
        secrets:
          registry-user: ${{ secrets.REGISTRY_USER }}
          registry-token: ${{ secrets.REGISTRY_TOKEN }}

    sonar:
        needs: tests
        uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/dotnet-sonar.yml@main
        with:
          project-key: ${{ vars.SONAR_PROJECT_KEY }}
        secrets:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          registry-user: ${{ secrets.REGISTRY_USER }}
          registry-token: ${{ secrets.REGISTRY_TOKEN }}

    publish:
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      needs: 
        - format
        - tests
        - sonar
      uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/dotnet-publish-global-nuget.yml@main
      secrets:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    notify:
      if: ${{ always() && github.event_name != 'pull_request' }}
      needs: [ publish ]
      uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/notify-telegram.yml@main
      with:
        event-name: ${{ github.event_name }}    
      secrets:
        telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        telegram-chat-id: ${{ vars.TELEGRAM_CHAT_ID }}
        github-token: ${{ secrets.REGISTRY_TOKEN }}
