<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>false</IsTestProject>
        <SonarQubeTestProject>true</SonarQubeTestProject>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup Condition="'$(UsePackedDomain)' != 'true'">
        <ProjectReference Include="../../src/PANiXiDA.Core.Domain/PANiXiDA.Core.Domain.csproj" />
        <ProjectReference Include="../../src/PANiXiDA.Core.Domain.Generators/PANiXiDA.Core.Domain.Generators.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup Condition="'$(UsePackedDomain)' == 'true'">
        <PackageReference Include="PANiXiDA.Core.Domain" VersionOverride="$(DomainPackageVersion)" />
    </ItemGroup>
</Project>
